### ISSUE TITLE
1.0 Milestone release TODO

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-js#1]
Lets create a list of things we need to get done before we consider this ready. Please feel free to add/modify and comment as needed. 

- [x] Change package name to @oh
- [x] Publish to NPM
- [x] Add webpack target 
- [x] Remove openHAB 1.x/2.x code 
- [ ] Improve README for users
- [x] Implement missing triggers 
- [x] Get TravisCI Working again
- [x] Get tests passing

**Comment by jpg0** [comment]
@digitaldan I've just realised that originally I also created https://github.com/jpg0/ohj-support to supply a few bits that I needed for the JS library that were not in openHAB itself. I believe that the bulk of it is no longer required, but I'd suggest that any dependency outside openHAB itself should be removed (or the support for it moved into openHAB).

**Comment by digitaldan** [comment]
Sounds good, afaik i have been running ohj with only small tweaks without that addon and everything worked great.  I'm just now submitting a few PR's with my changes.  If you could review them and give me feedback, that would be awesome.  Also I would love to hear what you think needs to be done to get this to 1.0 ?  I'll probably open tickets up if i have questions in the code.  Thanks for all the hard work, this is a really great library.

**Comment by jpg0** [comment]
Something to think about for 1.0 - what to do with the fluent stuff?

My personal view is that the existing rule definition API is too verbose. Well, my use-case is that I want a script with (for example) timing schedules, or button rules, but with **one rule per line**. This is simple with the fluent API. My view of there this should go (and actually what I use now, although not in JS) is a convergence of the two - a more standard non-fluent API, but sufficiently concise to allow single line rule definitions.

**Comment by jpg0** [comment]
Another thing which is probably more future direction rather than API: should all native Java objects be wrapped? This is the approach that I have taken because of various wonky incompatibilities and idiosyncrasies between JS and the Java objects, but this approach was not universally supported by others as it leads to adding functionality in JS rather than Java (where it's available to all languages).

**Comment by digitaldan** [comment]
>Something to think about for 1.0 - what to do with the fluent stuff?

I was thinking to leave it in for now, i have been updating it as i add new trigger types, and i agree it makes writing rules more concise.  One feature i wanted to discuss was being able to supply an optional name to fluent rules, technically this is not a problem, but I struggled with what to call it, and where to put it in the fluent syntax that was not awkward. 

>is a convergence of the two - a more standard non-fluent API,

 yeah, having one way would make more sense (especially in documentation) .  Honestly, if we could give fluent a rule name and description option in the syntax,  I would be comfortable making this just our default rules syntax and we could drop the "fluent" name, wdyt?  I'm trying to think what the JSRules syntax gives us over the fluent one?  

>Another thing which is probably more future direction rather than API: should all native Java objects be wrapped? 

I think it's worth talking about.  Would be good to understand what  idiosyncrasies there are currently and what the proposal would be.

**Comment by jpg0** [comment]
The lack of names in the fluent stuff I completely agree with. This also bothered me, and the existing name generation stuff isn't great. For adding the name, I'd suggest either something at the end `...named(<name>)`, or something at the start `rule(<name>).when(...` (or both). Something else that has also bothered me is the reliance on `with`, which is deprecated in JS (interestingly because it essential does a kind of variable 'injection' which makes it hard to understand, just like the original JS addon!). It may be possible to rewrite the flluent API to make everything chain from `rule`, in which case you could get rid of any other imports (and `with`). But yes I agree that there should be one syntax, and I certainly use the fluent one more, so would support removing the other one.

> I think it's worth talking about. Would be good to understand what idiosyncrasies there are currently and what the proposal would be.

Yeah let's not worry about this one too much for the moment.

**Comment by digitaldan** [comment]
> It may be possible to rewrite the flluent API to make everything chain from rule

Agreed.  So for example, 
`when(timeOfDay("SUNSET")).then(sendOn().toItem("KitchenLight"));`  
how would you propose to reference `timeOfDay` and `sendOn` ?

**Comment by jpg0** [comment]
It would have to be chained:

`when().timeOfDay("SUNSET").then().sendOn().toItem("KitchenLight");`

I'm not sure if that would cause problems for other expressions or not (oh and the function invocations could be avoided to instead do `when.timeOfDay(...` if it makes it more readable).

**Comment by digitaldan** [comment]
That makes sense, so `when()` would return a condition object/chain, and then calling `then()` on the last condition would return a command object/chain.  

Just to coordinate, is this something you want to tackle?  😄

**Comment by jpg0** [comment]
Yes, that is correct. Also I apologise that it's not something that I want to work on: I first need to get the add-on to run scripts from `<openhab-config>/automation/js` and modules the `node_modules` subdirectory of it. I have had no time to devote to this (super busy right now) but I regard it as top priority as it will force a migration for existing scripts.

**Comment by digitaldan** [comment]
Totally understand, i can give it a shot this week.  I agree that deprecating the `jsr232` path would be nice!

**Comment by jpg0** [comment]
The main reasons that I want to deprecate it are:
* It's not compatible with existing tooling (which expects modules to be in `node_modules`)
* It currently looks at `lib/javascript/personal`, not community etc, so isn't really compatible with the existing languages either

**Comment by digitaldan** [comment]
@jpg I have a first pass at moving fluent to what i'm calling the "Rule Builder" ,  you can see my branch at https://github.com/digitaldan/openhab-js/tree/rule-builder/rules , i combined the builder  with the existing rules logic which remains untouched,  So a rule might look like:

```javascript
rules.when().item("F1_DansOffice_Light").changed().then().send("changed").toItem("Echo_Dans_Office_TTS").build("Test Fluent 3", "Test 3");
```

or passing in a function and using a rule group:
```javascript
rules.when().item("F1_DansOffice_Light").changed().to("100").then(event => {
    log.info("F1_DansOffice_Light Event 2" + JSON.stringify(event));
}).inGroup("Fluent Test").build("Test Fluent 2", "Test 2");
```

the builder is exposed by calling `rules.when()`  , the last function `build(name, description)` will end the builder chain and save the rule. 

The existing fluent logic is still there as well as i'm testing this against my production system and it helps with the transition, but eventually that would be replaced by this. 

Let me know what you think, its a little bit of a hack job, so lots of room for improvement :-)

**Comment by jpg0** [comment]
Regarding the rule builder, do you think that it would be possible to allow providing the name at the start of the chain? 

`rule.of("TestFluent3").when().item("F1_DansOffice_Light").changed().then().send("changed").toItem("Echo_Dans_Office_TTS");`

Or similar? I ask because when I look at my rules I really want the name at the start as it's much simpler to parse a long block of these type of rules by scanning down the names on the LHS.

**Comment by jpg0** [comment]
@digitaldan something else to think about, not sure if it's a 1.0 thing or not, but I have certainly been asked about it:
- The current addon does not attempt to replace JS transforms at all - they still run in Nashorn

I think that incremental migration would be hard here (at they are just prefixed with `JS:`), but we could either register a new (temporary) prefix, or provide a configuration toggle to switch all transforms to the new engine. I have not looking into this at all.

I also saw that yesterday support was added for inline transforms, so JS directly in the transform string (rather than the filename), so there is work happening here. It would probably also be possible to allow much nicer, concise transform strings in ES6+ due to arrow functions.

**Comment by BobSilent** [comment]
> Regarding the rule builder, do you think that it would be possible to allow providing the name at the start of the chain?
> 
> `rule.of("TestFluent3").when().item("F1_DansOffice_Light").changed().then().send("changed").toItem("Echo_Dans_Office_TTS");`
> 
> Or similar? I ask because when I look at my rules I really want the name at the start as it's much simpler to parse a long block of these type of rules by scanning down the names on the LHS.

- would it be possible to also specify an optional Description or part of the description text?
description is an autogenerate text, which is partially nice, but in my case it says e.g. 
`item <itemname> changed→custom function`
- can the automatic generated ruleUID improved, e.g. add JS Filename instead of repeating description? e.g. `File_<filenameWithoutExtension>_<uid, maybe only 9chars like ui uid>`

- can the ruleUID also be available in the then function context?

**Comment by digitaldan** [comment]
>Regarding the rule builder, do you think that it would be possible to allow providing the name at the start of the chain?

I started off trying to do it this way actually, but the problem i faced is how to "end" the builder chain, i'm not sure how to know  when the chain is finished so we can execute it without using something like `build()`, do you have an idea on how this might work ?  I figured if we had to have `build` it might as well take the name/description and save a step. 

>The current addon does not attempt to replace JS transforms at all - they still run in Nashorn

Hmm i have not looked at that at all but also noticed the inline PR's lately as well.  I guess thats probably next on the list of things todo once we get this API locked down and documentation done.

>would it be possible to also specify an optional Description or part of the description text?

This is already there, `build()` takes two optional parameters, name and description, if you omit them, then they are autogenerated.  

>can the automatic generated ruleUID improved, e.g. add JS Filename instead of repeating description? e.g.

I'm not sure how the script would know its own filename?

**Comment by digitaldan** [comment]
@jpg0 did you have any thoughts here on ending a rule chain ?  I like your suggestion of using `of` and very curious if you have a solution.

**Comment by jpg0** [comment]
I think that there are a few options to do this:

- register the rule when the last thing is called, in this case `toItem`. This is one of the reasons for my more nested original approach, as you can do things like `then(send(..).toItem(..))` and you can do it in the `then`.
- create a new 'script complete' hook (like the script unloaded hook), and insert all the rules after the script is complete
- require an explicit step to insert rules, rather than when they are declared

The last option is an interesting one to me. I always found it odd that creation of a rule object also registered it with whatever processes it. This is not typical of most APIs - they would let you create this object, modify it, pass it around, store it, whatever, as distinct from actually registering it. The current behaviour I inherited from the original ES5 helper library, and never ended up changing it. I actually did modify it at one point (but didn't end up using it) as I wanted to provide my own `RuleProvider` to allow more control over the lifecycle of rules (and to more closely tie them with the lifecycle of the script), whereas now they are in a managed provider so technically have their own lifecycle outside that of the script (I saw the odd, benign, race condition on rules running after their script had been disposed). For my current system I actually did get rid of this automatic registration, and rules are explicitly added to a provider, but that is probably more control than most users require. Sorry, not sure that this actually helps you!

**Comment by JamieTemple** [comment]
sorry - a bit late to the party, but wanted to chip-in my 0.5p ...

I don't have a problem with ending on `.build()` - its a pretty standard builder pattern (which I'm quite fond of!)

... also, here's my take on how things could look:

```
rules
  .named("TestFluent2")
  .withDescription("Fluent rule builder example.")
  .inGroup("Fluent Test")
  .withTrigger(item("F1_DansOffice_Light").changed().to("100"))
  .withAction(event => {
    log.info("F1_DansOffice_Light Event 2" + JSON.stringify(event));
  })
  .build();
```

I appreciate things are out the door already (and this looks like ive spent way too much time writing unit test lately!) - feel free to ignore me ;)
